[package]
name = "api-db"
version = "0.1.0"
edition = "2021"

[dependencies]
api-lib = { workspace = true }
sqlx = { workspace = true }
actix-web = { workspace = true }
dotenv = { workspace = true }
tracing = { workspace = true }
color-eyre = { workspace = true }
