CREATE OR REPLACE USER 'user'@'localhost' IDENTIFIED BY 'password';
CREATE OR REPLACE USER 'user'@'172.17.0.1' IDENTIFIED BY 'password'; -- docker
GRANT ALL PRIVILEGES ON DigiTourLocal.* TO 'user'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON DigiTourLocal.* TO 'user'@'172.17.0.1' WITH GRANT OPTION; -- docker
FLUSH PRIVILEGES;
